### ISSUE TITLE
[Suggestion] User-hosted Lavalink node

### ISSUE THREAD

**Issue by kijk2869** [sannoob/Siru-stable#23]

**Comment by ReDesignedJP** [comment]
Already supported?

**Comment by ReDesignedJP** [comment]
Sorry I was confused

**Comment by sannoob** [comment]
유저가 호스팅하는 라바링크는 안정적이지 못하고, Lavalink 는 봇의 Voice Token을 이용하기 때문에 악용 가능.
만약 이 봇을 셀프 호스팅 하고싶다면 Clone 후 설정해서 사용 바랍니다
