### ISSUE TITLE
[버그] reply 멘션 작업할 때 escape되어서 표시가 됨.(ping,help command)

### ISSUE THREAD

**Issue by MoartMedia** [sannoob/Siru-stable#25]
![Screenshot_20200815-222924_Discord](https://user-images.githubusercontent.com/18746638/90313387-21be1980-df47-11ea-9ab5-02c85d7061c1.jpg)

뭔가 이상해서 소스를 보니
message.author로 되어 있긴 하나
이상하게 @ 옆에 빈칸 특수문자가 끼어서 escape 처리가 됬네요.
자세히 안 살펴봐서 왠지는 모르겠지만 내부 버그인 거 같아 제보합니다.

**Comment by wonderlandpark** [comment]
CNR
![image](https://user-images.githubusercontent.com/31924512/90313469-d35d4a80-df47-11ea-8774-8767c5ee6ed9.png)

**Comment by MoartMedia** [comment]
치노 공식 지원 서버만 그런거 같습니다. 다른 서버에는 영향이 없는 거 같으니 해당 이슈 닫습니다.

**Comment by sannoob** [comment]
봇 설정쪽에서 disableMentions 를 all 로 해놔서 일어난 일입니다, 처리 후 이슈 닫겠습니다

**Comment by sannoob** [comment]
수정되었습니다
