### ISSUE TITLE
[제안] 디스코드에서 재생중인 곡을 웹페이지에서도 듣는 기능

### ISSUE THREAD

**Issue by kijk2869** [sannoob/Siru-stable#48]
Opus 코덱 음질 개쓰레기에요
해주세요

**Comment by sannoob** [comment]
![image](https://user-images.githubusercontent.com/40298015/92671985-a0de1c00-f352-11ea-8537-b76b42aa978e.png)
![image](https://user-images.githubusercontent.com/40298015/92671994-a5a2d000-f352-11ea-88da-7fef9c527402.png)
?

**Comment by kijk2869** [comment]
아 디코 음질이 쓰레기란 뜻이에요

**Comment by sannoob** [comment]
> 아 디코 음질이 쓰레기란 뜻이에요

https://support.discord.com/hc/ko
