### ISSUE TITLE
레포 이름 수정

### ISSUE THREAD

**Issue by kijk2869** [sannoob/Siru-stable#50]
![image](https://user-images.githubusercontent.com/35522821/92672109-ec90c580-f352-11ea-8d6a-b05d5003dd7a.png)

![image](https://user-images.githubusercontent.com/35522821/92672107-e995d500-f352-11ea-8f24-2bdc466a2a7f.png)

?

**Comment by SaidBySolo** [comment]
코드네임 모르시네

**Comment by Yoruroong** [comment]
https://namu.wiki/w/%EC%BD%94%EB%93%9C%EB%84%A4%EC%9E%84(%EB%B3%B4%EB%93%9C%20%EA%B2%8C%EC%9E%84)

**Comment by sannoob** [comment]
아니 인증된 봇 이름이 안바뀐다고요
